### ISSUE TITLE
Cookbook does not work with encrypted data bags

### ISSUE THREAD

**Issue by sgtsquiggs** [fnichol/chef-user#75]
Doesn't seem to work anyway:

```
Chef::Exceptions::ValidationFailed
----------------------------------
Option comment must be a kind of String!  You passed {"encrypted_data"=>"CqvxeieeVoHvx98kgglg06hsqnx2mN/wp9u1gCaPfERnL218h4hraMyF+qKl\n4sNf\n", "iv"=>"CcVBWx/mLmaJUrxjARS3Bw==\n", "version"=>1, "cipher"=>"aes-256-cbc"}.

Cookbook Trace:
---------------
  /home/vagrant/chef-solo/cookbooks-2/user/recipes/data_bag.rb:39:in `block (3 levels) in from_file'
  /home/vagrant/chef-solo/cookbooks-2/user/recipes/data_bag.rb:37:in `each'
  /home/vagrant/chef-solo/cookbooks-2/user/recipes/data_bag.rb:37:in `block (2 levels) in from_file'
  /home/vagrant/chef-solo/cookbooks-2/user/recipes/data_bag.rb:36:in `block in from_file'
  /home/vagrant/chef-solo/cookbooks-2/user/recipes/data_bag.rb:32:in `each'
  /home/vagrant/chef-solo/cookbooks-2/user/recipes/data_bag.rb:32:in `from_file'
```

**Comment by theckman** [comment]
There is value in getting this to work with encrypted data bags, probably as well as look at adding support for `chef-vault`.
