### ISSUE TITLE
Support for whyrun on user_account provider

### ISSUE THREAD

**Issue by tatemz** [fnichol/chef-user#82]
Any chance support for whyrun on `user_account` could be added, please? Really been relying on whyruns these days for quality assurance. Share the whyrun love!

**Comment by ranjib** [comment]
should be available on 0.4 release onwards.

**Comment by patcon** [comment]
I'm getting an error with whyrun too in 0.4.2:

```
* user_account[patcon] action create
* directory[/home/patcon parent directory] action create (up to date)
* user[patcon] action create
- Would create user patcon

================================================================================
Error executing action `create` on resource 'user_account[patcon]'
================================================================================

ArgumentError
-------------
can't find user for patcon

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/user/providers/account.rb:134:in `getpwnam'
/var/chef/cache/cookbooks/user/providers/account.rb:134:in `block in home_dir_resource'
/var/chef/cache
```

**Comment by patcon** [comment]
This is resolved by an unreleased commit:
https://github.com/fnichol/chef-user/commit/7d445eda70985d0bb8aeb5998dcdf9d613f81735
